select concat('insert into photo.photo (
    id, 
    category_id,
    is_private,
    xs_height,
    xs_width,
    xs_path,
    sm_height,
    sm_width,
    sm_path,
    md_height,
    md_width,
    md_path,
    lg_height,
    lg_width,
    lg_path,
    src_height,
    src_width,
    src_path,
    prt_height,
    prt_width,
    prt_path
    ) values (', 
    id, ', ',
    photo_category_id, ', ',
    'CAST(', is_private, ' AS BOOLEAN), ',
    thumb_height, ', ',
    thumb_width, ', ',
    '''', thumbnail_path, ''', ',
    full_height, ', ',
    full_width, ', ',
    '''', fullsize_path, ''', ',
    fuller_height, ', ',
    fuller_width, ', ',
    '''', fuller_path, ''', ',
    orig_height, ', ',
    orig_width, ', ',
    '''', REPLACE(orig_path, '/orig/', '/lg/'), ''', ',
    orig_height, ', ',
    orig_width, ', ',
    CONCAT('''', COALESCE(raw_path, REPLACE(orig_path, '/orig/', '/src/')), ''''), ', ',
    orig_height, ', ',
    orig_width, ', ',
    '''', REPLACE(orig_path, '/orig/', '/prt/'), '''',
    ');')
from photo;

select concat('alter sequence photo.photo_id_seq restart with ', max(id) + 1, ';') from photo;
