# originally based on: https://github.com/nsubstitute/NSubstitute/blob/9f2323f4885d96ff863d0e26cc32b652b09ee930/.travis.yml
# updated based on: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/using-ci-with-cli
language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.1.0
      env: CONFIGURATION=Debug FRAMEWORK=netcoreapp1.1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.1.0
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp1.1

script:
  - cd src/mikeandwan.us
  - dotnet restore
  - dotnet build -c $CONFIGURATION -f $FRAMEWORK
