language: csharp
solution: mikeandwan.us.sln
mono: none
dotnet: 1.0.1

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: CONFIGURATION=Debug DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      env: CONFIGURATION=Release DOTNETCORE=1

script:
  - cd src
  - dotnet restore
  - cd mikeandwan.us
  - dotnet build -c $CONFIGURATION
