language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: none
      dotnet: 2.1.300-preview1-008174
      env: CONFIGURATION=Debug DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      mono: none
      dotnet: 2.1.300-preview1-008174
      env: CONFIGURATION=Release DOTNETCORE=1

script:
  - dotnet restore
  - dotnet build -c $CONFIGURATION mikeandwan.us.sln
