language: csharp
solution: mikeandwan.us.sln

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: none
      dotnet: 1.0.1
      env: CONFIGURATION=Debug DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      mono: none
      dotnet: 1.0.1
      env: CONFIGURATION=Release DOTNETCORE=1
