version: '3'

services:
  auth:
    image: maw/auth
    network_mode: "host"
    build:
      context: .
      dockerfile: src/auth/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - MAW_AUTH_Environment__DbConnectionString
      - MAW_AUTH_GooglePlus__ClientId
      - MAW_AUTH_GooglePlus__ClientSecret
      - MAW_AUTH_Twitter__ConsumerKey
      - MAW_AUTH_Twitter__ConsumerSecret
      - MAW_AUTH_Microsoft__ApplicationId
      - MAW_AUTH_Microsoft__Secret
      - MAW_AUTH_GitHub__ClientId
      - MAW_AUTH_GitHub__ClientSecret

  api:
    image: maw/api
    network_mode: "host"
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "5011:5011"
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - MAW_API_Environment__DbConnectionString

  www:
    image: maw/www
    network_mode: "host"
    build:
      context: .
      dockerfile: src/www/Dockerfile
    ports:
      - "5021:5021"
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - MAW_WWW_Environment__DbConnectionString
      - MAW_WWW_Email__User
      - MAW_WWW_Email__Password
      - MAW_WWW_GoogleRecaptcha__SiteKey
      - MAW_WWW_GoogleRecaptcha__SecretKey

