[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1014")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1031")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1303")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1848")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA2201")]
