[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1031")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1055")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1056")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1303")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1801")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1822")]
