FROM nginx:alpine

COPY etc/nginx/proxy.conf                 /etc/nginx
COPY etc/nginx/tls.conf                   /etc/nginx
COPY etc/nginx/dev.nginx.conf             /etc/nginx/nginx.conf
COPY etc/nginx/conf.d/dev.maw-photos.conf /etc/nginx/conf.d/maw-photos.conf

CMD [ "nginx", "-g", "daemon off;" ]
EXPOSE 80, 443
