FROM nginx:alpine

RUN rm /etc/nginx/conf.d/*

COPY etc/nginx/proxy.conf                 /etc/nginx
COPY etc/nginx/tls.conf                   /etc/nginx
COPY etc/nginx/dev.nginx.conf             /etc/nginx/nginx.conf
COPY etc/nginx/conf.d/dev.maw-api.conf    /etc/nginx/conf.d/maw-api.conf
COPY etc/nginx/conf.d/dev.maw-auth.conf   /etc/nginx/conf.d/maw-auth.conf
COPY etc/nginx/conf.d/dev.maw-files.conf  /etc/nginx/conf.d/maw-files.conf
COPY etc/nginx/conf.d/dev.maw-photos.conf /etc/nginx/conf.d/maw-photos.conf
COPY etc/nginx/conf.d/dev.maw-www.conf /etc/nginx/conf.d/maw-www.conf

CMD [ "nginx", "-g", "daemon off;" ]

EXPOSE 80, 443
