namespace Maw.TagHelpers
{
    public enum SvgIcon
    {
        Android,
        At,
        Bars,
        Camera,
        CaretDown,
        Check,
        Cog,
        Download,
        Envelope,
        Facebook,
        Flag,
        Github,
        GooglePlus,
        GooglePlusSquare,
        Group,
        LinkedIn,
        Lock,
        Person,
        Steam,
        Trash,
        Trello,
        Twitter,
        UnlockAlt,
        Upload,
        VideoCamera,
        Windows,
        Wrench
    }
}
