[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1002")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1014")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1031")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1303")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1308")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1801")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1814")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1822")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1848")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA2201")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "SCS0012")]
