[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1014")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1303")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1707")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1822")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA2201")]
