[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1002")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1031")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1054")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1056")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1822")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "CA1848")]
